fridges:
  - fridge_id: fridge_1
    nickname: "fridge_1_nickname"
    password: "dummy_pass"
    server_address: "127.0.0.1"
    server_port: 9001

  - fridge_id: fridge_2
    nickname: "fridge_2_nickname"
    password: "dummy_pass"
    server_address: "127.0.0.1"
    server_port: 9002
